"""The consuming project's generated `CLAUDE.md` (spec Sec.5.2).

Sec.5.2's project layout lists `CLAUDE.md` as "thin; generated; points at
the profile" - living in the *project*, not in this repo. It was never
built. A project could therefore be fully installed and fully profiled and
still give a session no automatic pointer to any of it: the skills load,
but nothing says this project has a profile, where it is, or that the model
files are not editable by hand.

Thin is the operative word. Everything project-specific stays in
`se-buddy/`, which is read by verbs rather than by prose; this file only
says where to look and which rules always apply. It carries no
architectural content, so regenerating it can never lose engineering
judgement - which is what makes the managed-block approach below safe.

**Non-destructive by construction.** The generated text lives between two
HTML-comment markers and nothing outside them is ever touched:

  - no `CLAUDE.md`            -> create one containing the block
  - `CLAUDE.md` with the block -> replace the block, leave the rest alone
  - `CLAUDE.md` without it     -> append the block, leave the rest alone

So there is no overwrite case to guard, and no `--force` to get wrong.
That is also why this verb is not TTY-gated, unlike `write-profile` and
`write-domain`: it asserts nothing the engineer has to judge, and it cannot
destroy anything they wrote. It is the same carve-out spec Sec.7.3 gives
`write propose` and `se_buddy.scaffold` - authority follows what the write
can assert and what it can lose, not the fact that it touches a file.
"""

from __future__ import annotations

import re
from pathlib import Path

from se_buddy.atomic_write import atomic_write_text

BEGIN = "<!-- se-buddy:begin -->"
END = "<!-- se-buddy:end -->"

_BLOCK = re.compile(
    re.escape(BEGIN) + r".*?" + re.escape(END),
    re.DOTALL,
)

_TEMPLATE = """\
{begin}
<!-- Generated by `se-buddy write-claude-md`. Edits inside this block are
     replaced on the next run; everything outside it is left alone. -->

## SE Buddy (MBSE / Eclipse Capella)

{project_line}

Model-based systems engineering in this project goes through
[SE Buddy](.claude/skills/se-buddy/), using the Arcadia method. The skills
are namespaced `/se-buddy:<name>`; run `/se-buddy:doctor` if any of them
fail to resolve.

**Project context lives in `se-buddy/`, not in this file.** Read it with
the verbs rather than by opening the files:

| Where | What it holds | Read it with |
| --- | --- | --- |
| `se-buddy/profile.yaml` | model paths, Capella version, project name | `se-buddy doctor` |
| `se-buddy/domain.md` | the domain pack — standards, attack surfaces, verification patterns (spec Sec.5.4) | read directly |
| `se-buddy/viewpoints.yaml` | non-functional concerns, design rules, priority order | `se-buddy memory viewpoints` |
| `se-buddy/principles.yaml` | the project's standing rules | `se-buddy memory principles` |
| `se-buddy/registers/` | risks, requirements, stakeholder expectations, verification, not-carried | `se-buddy register <name>` |
| `se-buddy/decisions/` | ADRs | `se-buddy memory decisions` |

**Rules that hold in every session here:**

- **Never edit {model_files} directly.** The semantic model changes only
  through `se-buddy write-propose` → `write-apply`; the `.aird` holds
  diagrams placed by hand and is read-only to tooling. A `PreToolUse` hook
  blocks direct edits, but the rule stands whether or not it fires.
- **Every `se-buddy write-*` verb except `write-propose` refuses outside an
  interactive terminal.** Draft the input, then hand the command to the
  engineer to run — scripting one will fail, by design, not by accident.
- **The engineer makes every architecture decision.** This tooling advises
  and records; it does not decide.
- **State when the profile is incomplete.** `se-buddy doctor` reports open
  `SUPPLY` asks; while any are open, architectural judgements say the
  project style is unrecorded rather than assuming one.

{end}
"""


def render(profile: dict | None) -> str:
    """Renders the managed block. `profile` may be None or partial."""
    profile = profile or {}
    name = profile.get("project_name")
    model = profile.get("model_path")
    aird = profile.get("aird_path")
    version = profile.get("capella_version")

    if name and model and version:
        project_line = f"**{name}** — `{model}` (Capella {version})."
    elif name:
        project_line = f"**{name}**."
    else:
        # Said plainly rather than papered over: a reader needs to know the
        # profile is not filled in yet, and `doctor` is where that is fixed.
        project_line = (
            "This project's `se-buddy/profile.yaml` is not complete yet — "
            "run `/se-buddy:project-init`."
        )

    model_files = (
        f"`{model}` or `{aird}`" if model and aird else "the `.capella` or `.aird` files"
    )

    return _TEMPLATE.format(
        begin=BEGIN, end=END, project_line=project_line, model_files=model_files
    )


def apply_block(existing: str | None, block: str) -> tuple[str, str]:
    """Returns (new text, what happened) for one of the three cases."""
    if existing is None:
        return block, "created"
    if _BLOCK.search(existing):
        return _BLOCK.sub(lambda _: block.rstrip("\n"), existing), "updated in place"
    separator = "" if existing.endswith("\n\n") else ("\n" if existing.endswith("\n") else "\n\n")
    return existing + separator + block, "appended"


def write(root: Path, profile: dict | None) -> tuple[Path, str]:
    """Writes the project's `CLAUDE.md`. Returns (path, what happened)."""
    path = root / "CLAUDE.md"
    existing = path.read_text(encoding="utf-8") if path.is_file() else None
    text, action = apply_block(existing, render(profile))
    atomic_write_text(path, text)
    return path, action
